export { default as AboutPage } from './about'
export { default as CalendarPage } from './calendar'
export { default as HomePage } from './home'
export { default as LoginPage } from './login'
export { default as ProfilePage } from './profile'
export { default as TasksPage } from './tasks'
